name: Build and Test

on:
  push:
    branches: [ master ]
    paths:
    - 'src'
    - '.github'
  pull_request:
    branches: [ master ]
    paths:
    - 'src'
    - '.github'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/GingerbreadAI.NeuralNetwork.Test.sln
    - name: Build
      run: dotnet build src/GingerbreadAI.NeuralNetwork.Test.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/GingerbreadAI.NeuralNetwork.Test.sln --no-restore --verbosity normal
