name: Publish Convolutional Neural Network to NuGet

on:
  push:
    branches: [ main ]
    paths:
    - 'src/Model/GingerbreadAI.Model.ConvolutionalNeuralNetwork/**'
    - '.github/workflows/ci_publish-convolutional-neural-network.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'src/Model/GingerbreadAI.Model.ConvolutionalNeuralNetwork/**'
    - '.github/workflows/ci_publish-convolutional-neural-network.yml'

env:
  PROJECT_LOCATION: src/Model/GingerbreadAI.Model.ConvolutionalNeuralNetwork/
  PROJECT_FILE: GingerbreadAI.Model.ConvolutionalNeuralNetwork.csproj

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
        source-url: https://nuget.pkg.github.com/benchiverton/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # suffix the package with the run number if building from a PR
    - name: Pack Pre-Release
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      run: dotnet pack ${{ env.PROJECT_LOCATION }}${{ env.PROJECT_FILE }} --configuration Release --include-symbols --version-suffix pr${{ github.RUN_NUMBER }} 
    - name: Pack Release
      if: github.event_name == 'push'
      run: dotnet pack ${{ env.PROJECT_LOCATION }}${{ env.PROJECT_FILE }} --configuration Release --include-symbols
    - name: Publish
      run: dotnet nuget push ${{ env.PROJECT_LOCATION }}bin/Release/*.nupkg --skip-duplicate
